In [2]:
import numpy as np
import pandas as pd

In [10]:
dataframe = pd.DataFrame(np.random.randint(-25,25, size=(4,4)), index=["L1","L2","L3","L4"],columns=["C1","C2","C3","C4"])
print(dataframe)
dataframe["C4"] += 5
dataframe

    C1  C2  C3  C4
L1   3 -18  -8 -25
L2   4   2  18  13
L3  -7  20  19  -5
L4   2 -14 -22   2

    C1  C2  C3  C4
L1   3 -18  -8 -20
L2   4   2  18  18
L3  -7  20  19   0
L4   2 -14 -22   7

In [14]:
dataframe.abs()

    C1  C2  C3  C4
L1   3  18   8  20
L2   4   2  18  18
L3   7  20  19   0
L4   2  14  22   7

In [19]:
dataframe = pd.DataFrame(np.random.randint(-25,25, size=(5,5)),
                         index=["L1","L2","L3","L4","L5"],
                         columns=["C1","C2","C3","C4","C5"])
print(dataframe)
dataframe.median(axis=1)

    C1  C2  C3  C4  C5
L1  10 -11 -15  -7 -22
L2  -9  16  -5   4  24
L3   3   8  17 -11   3
L4  22  15  15 -22  14
L5   4  -1  10  11  24

L1   -11.0
L2     4.0
L3     3.0
L4    15.0
L5    10.0
dtype: float64

In [ ]:
dataframe = pd.DataFrame(np.random.randint(-25,25, size=(5,5)),
                         index=["L1","L2","L3","L4","L5"],
                         columns=["C1","C2","C3","C4","C5"])
print(dataframe)
print(dataframe > 0)
print(dataframe[dataframe > 0])
print(dataframe.loc[:,"C1":"C3"]>5)

funcion_especial = lambda x: x**2 - 5
print(dataframe.C3.apply(funcion_especial))

    C1  C2  C3  C4  C5
L1  15   7  15 -25 -19
L2   8 -20   7  15  15
L3  10   1   1   2  21
L4  22   0  19  22  -5
L5  14   0  14  -9  20
      C1     C2    C3     C4     C5
L1  True   True  True  False  False
L2  True  False  True   True   True
L3  True   True  True   True   True
L4  True  False  True   True  False
L5  True  False  True  False   True
    C1   C2  C3    C4    C5
L1  15  7.0  15   NaN   NaN
L2   8  NaN   7  15.0  15.0
L3  10  1.0   1   2.0  21.0
L4  22  NaN  19  22.0   NaN
L5  14  NaN  14   NaN  20.0
      C1     C2     C3
L1  True   True   True
L2  True  False   True
L3  True  False  False
L4  True  False   True
L5  True  False   True
L1    220
L2     44
L3     -4
L4    356
L5    191
Name: C3, dtype: int64

In [ ]:
serie = pd.Series([1,2,3,4,5,6,7,8,9], index=["a","b","c","d","e","f","g","h","i"])
print("Valor item de la posicion 5:", serie.loc["f"])
#
# Valor item de la posicion 5: 6

Valor item de la posicion 5: 6

In [9]:
dataframe = pd.DataFrame(np.random.randint(5, size=(8,8)),
                           index=["L1","L2","L3","L4","L5","L6","L7","L8"],
                           columns=["C1","C2","C3","C4","C5","C6","C7","C8"]
                           )
 
dataframe.drop("L4") # eliminar la fila con indice L4
dataframe.drop(columns=["C2","C6"]) # eliminar las columnas C2 y C6
print("Sin inplace = True el dataset se mantiene íntegro")
print(dataframe) # sin inplace = True el dataset se mantiene íntegro.
dataframe.drop("L4", inplace=True)
dataframe.drop(columns=["C2","C6"], inplace=True)
print("\nCon inplace = True el dataset se ha alterado")
print(dataframe) # con inplace = True el dataset original ha sido alterado.

Sin inplace = True el dataset se mantiene íntegro
    C1  C2  C3  C4  C5  C6  C7  C8
L1   1   4   1   4   4   4   2   1
L2   0   1   0   3   3   4   0   4
L3   2   0   3   4   1   2   1   1
L4   4   0   1   0   4   1   2   4
L5   2   1   0   3   1   0   2   0
L6   3   1   1   2   3   0   4   1
L7   3   4   1   1   1   0   3   1
L8   3   4   1   1   1   2   1   1

Con inplace = True el dataset se ha alterado
    C1  C3  C4  C5  C7  C8
L1   1   1   4   4   2   1
L2   0   0   3   3   0   4
L3   2   3   4   1   1   1
L5   2   0   3   1   2   0
L6   3   1   2   3   4   1
L7   3   1   1   1   3   1
L8   3   1   1   1   1   1